### ISSUE TITLE
Upvote ADT4J!

### ISSUE THREAD

**Issue by jbgi** [sviperll/adt4j#21]
https://github.com/akullpp/awesome-java/pull/148

**Comment by sviperll** [comment]
Nice birthday present. But what should I do to upvote it?

**Comment by jbgi** [comment]
+1, but that would need to be @talios (or other atd4j users job), since you are the author and cannot upvote yourself (I think). Happy birthday!

**Comment by talios** [comment]
How does one +1 it? Other than the comment I just added saying +1!

**Comment by jbgi** [comment]
yep, that's it.

**Comment by jbgi** [comment]
ADT4J is now listed on awesome-java!

**Comment by sviperll** [comment]
Awesome!
