### ISSUE TITLE
2.0.1-shaded causes javac errors

### ISSUE THREAD

**Issue by talios** [sviperll/adt4j#26]
Under both java 7 and 8, I seem to get the following error using the shaded version.  2.0.1 non-shaded works fine.

    [INFO] Compiling 28 source files to /Users/amrk/IdeaProjects/securemx/smx3/smx3.reporting.common/target/classes
    An exception has occurred in the compiler (1.7.0_80). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
    com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.github.sviperll.adt4j.internal.java.lang.Object not found

**Comment by sviperll** [comment]
Wow. It seems that it tries to shade and relocate java.lang package. Do you use adt4j jar's from maven central or you have built it yourself?

**Comment by sviperll** [comment]
It should be fixed in 2.0.2. But there are some design issues with shaded artifact, it exports some classes from `com.github.sviperll.meta` package, not `com.github.sviperll.adt4j`

**Comment by talios** [comment]
@sviperll I see you've fixed it ( cheers ), but for reference that was from the maven central release.
