### ISSUE TITLE
Generate as musch as possible even in presence of compilation errors.

### ISSUE THREAD

**Issue by sviperll** [sviperll/adt4j#29]
Compilation errors poorly interacts with ADT4J. Any single compilation error usually causes an avalanche of "class not defined" and "method not defined" errors.

It should be better to generate as much as possible even in presence of compilation errors. It should be better to generate method that always throws UnsupportedOperationException than not to generate method at all.

Compilation shouldn't succeed in presence of errors, but root cause should be reported as an error without unnecessary noise.

**Comment by jbgi** [comment]
:+1:
Alternative is to run annotation processing separately, ie. through maven-apt-plugin but this add some complexity to the build.
