### ISSUE TITLE
universal-maven-parent not deployed to Central

### ISSUE THREAD

**Issue by io7m** [sviperll/adt4j#36]
Hello.

I attempted to use 3.0-rc1 today, but discovered that the parent of the `adt4j-maven-parent` project isn't in Maven Central yet, and so the package can't be used.

```Failed to collect dependencies at com.github.sviperll:adt4j-shaded:jar:3.0-rc1: Failed to read artifact descriptor for com.github.sviperll:adt4j-shaded:jar:3.0-rc1: Could not find artifact com.github.sviperll:universal-maven-parent:pom:0.18```

**Comment by sviperll** [comment]
3.0-rc2 should work. Sorry for inconvenience.

**Comment by io7m** [comment]
No problem. Thanks!

**Comment by talios** [comment]
And 3.0.1 fails for a similar reason:

    dependencies at com.github.sviperll:adt4j:jar:3.0.1 -> com.github.sviperll:chicory-core:jar:0.29:
    Failed to read artifact descriptor for com.github.sviperll:chicory-core:jar:0.29: Could not find artifact
    com.github.sviperll:maven-parent:pom:0.17 in Nexus

Will raise this separately tho,
