### ISSUE TITLE
maven-parent 0.17 not deployed to maven central

### ISSUE THREAD

**Issue by talios** [sviperll/adt4j#37]
Trying to use the new 3.0.1 release:

    dependencies at com.github.sviperll:adt4j:jar:3.0.1 -> com.github.sviperll:chicory-core:jar:0.29:
    Failed to read artifact descriptor for com.github.sviperll:chicory-core:jar:0.29: Could not find artifact
    com.github.sviperll:maven-parent:pom:0.17 in Nexus

Only 0.16 is released to maven central.

**Comment by sviperll** [comment]
It's... sad... There should be a way to automate this check... I've released 3.0.2 with correct dependencies though...
