### ISSUE TITLE
Support for default values

### ISSUE THREAD

**Issue by talios** [sviperll/adt4j#7]
Often, I'm finding I'd like to define some default values, which would be used in conjunction with an `@Updater` annotation, which would be elided from the constructor method for a type, something like:

    R standard(String name, @Updater("titled") String title,
      @DefaultValue("false") @Updater("hidden") boolean hidden,
      @DefaultValue("false") @Updater("grouped") boolean grouped,
      @DefaultValue("FieldSortOrder.NATURAL") @Updater("sortedBy") FieldSortOrder sortOrder);

Would generate a method to be called in a manner such as:

    MyValue.standard("name", "title")
                  .sortedBy(FieldSortOrder.ASCENDING);

Currently, I'm writing wrapping functions in another class that do just this, and I'm torn between whether this should lifted into a generic facility of ADJ4J or not.

Thoughts?

**Comment by sviperll** [comment]
In 0.13 version extending generated classes should bring no performance penalty. I suggest that you try to extend generated classes to add convenience factory-methods.

**Comment by sviperll** [comment]
I'm considering to mark this issue as "Won't Fix". As I see no clean proposals except manually extending generated class. Do you agree, @talios?

**Comment by talios** [comment]
I think I'm fine with that. I'm currently thinking of ways we could utilize Java 8 default methods for improving the `MyOptional` style extension methods - I have some ideas on that but none of them are overly nice at the moment :(
