### ISSUE TITLE
Reuse visitor instances in getter methods

### ISSUE THREAD

**Issue by sviperll** [sviperll/adt4j#9]
String getName() {
        return this.accept(new UserVisitor<String>() {
            @Override
            public String of(String name, int age) {
                return name;
            }
        });
    }

should probably become

    private static final UserVisitor<String> GET_NAME_VISITOR = new UserVisitor<String>() {
         @Override
         public String of(String name, int age) {
             return name;
         }
     };
    String getName() {
        return this.accept(GET_NAME_VISITOR);
    }

in generated code

**Comment by sviperll** [comment]
I've just released 0.13 version. It has been refactored to deliver almost no allocations in generated methods.

**Comment by talios** [comment]
+1000! Awesome. Will update and check out the new code and report back.

**Comment by talios** [comment]
Just checked the new generated code - +1000 ontop of that earlier 1000. That's looking much nicer, and from what I can see (without running benchmarks) my code which does A LOT of iteration of A LOT of ADT4j instances seems to be running MUCH MUCH faster.

What the hell - have another +1000 :)

**Comment by sviperll** [comment]
What's your opinion about generated code for equals and compareTo. Should we try to improve it? Should we try to get read of boolean and int boxing? Or should we better live current version as is?

**Comment by jbgi** [comment]
I just noticed there is a little problem with the generated *AcceptorEqualsVisitor classes: they do not implement Serializable even though valueClassIsSerializable is at true.

**Comment by sviperll** [comment]
@jbgi Can you test HEAD of master? It should be fixed now.
